/*Generated by WaveMaker Studio*/

package com.vcs.highscoredb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.vcs.highscoredb.Table101;

/**
 * Service object for domain model class Table101.
 *
 * @see {@link Table101}
 */
public interface Table101Service {

    /**
     * Creates a new Table101.
     *
     * @param table101 The information of the created CompositeTable.
     * @return The created Table101.
     */
	Table101 create(Table101 table101);


	/**
	 * Finds Table101 by id.
	 *
	 * @param table101Id The id of the wanted Table101.
	 * @return The found Table101. If no Table101 is found, this method returns null.
	 */
	Table101 getById(Integer table101Id) throws EntityNotFoundException;


	/**
	 * Updates the information of a Table101.
	 *
	 * @param table101 The information of the updated Table101.
	 * @return The updated Table101.
     *
	 * @throws EntityNotFoundException if no Table101 is found with given id.
	 */
	Table101 update(Table101 table101) throws EntityNotFoundException;

    /**
	 * Deletes a Table101.
	 *
	 * @param table101Id The id of the deleted Table101.
	 * @return The deleted Table101.
     *
	 * @throws EntityNotFoundException if no Table101 is found with the given id.
	 */
	Table101 delete(Integer table101Id) throws EntityNotFoundException;

	/**
	 * Finds all Table101s.
	 *
	 * @return A list of Table101s.
	 */
    @Deprecated
	Page<Table101> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Finds all Table101s.
	 * @return A list of Table101s.
	 */
    Page<Table101> findAll(String query, Pageable pageable);

    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Table101s in the repository with matching query.
     *
     * @param query query to filter results.
	 * @return The count of the Table101.
	 */
	long count(String query);


}

