/*Generated by WaveMaker Studio*/

package com.vcs.highscoredb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Table101 generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`TABLE101`")
public class Table101 implements Serializable {

    private int id;
    private String sdsdsds;
    private String column3;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "`sdsdsds`", nullable = true, length = 255)
    public String getSdsdsds() {
        return this.sdsdsds;
    }

    public void setSdsdsds(String sdsdsds) {
        this.sdsdsds = sdsdsds;
    }

    @Column(name = "`COLUMN3`", nullable = true, length = 255)
    public String getColumn3() {
        return this.column3;
    }

    public void setColumn3(String column3) {
        this.column3 = column3;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Table101)) return false;
        final Table101 table101 = (Table101) o;
        return Objects.equals(getId(), table101.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

